name: "Run checks: all modules"

on: 
  workflow_dispatch:

  pull_request:
    branches:
      - '*'

  push:
    branches:
      - 'main'
      - 'branch_10x'

env:
  DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_ACCESS_KEY }}

# We split the workflow into two parallel jobs for efficiency:
# one is running all validation checks without tests,
# the other runs all tests without other validation checks.

jobs:

  # This runs all validation checks without tests.
  checks:
    name: checks without tests (JDK ${{ matrix.java }} on ${{ matrix.os }})
    timeout-minutes: 15

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        java: [ '23' ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Correct git autocrlf
        run: git config --global core.autocrlf false

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ./.github/actions/prepare-for-build

      - name: Run gradle check (without tests)
        run: ./gradlew checkLicenses checkLocks

